# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_sitemap}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BrowserMedia"]
  s.date = %q{2010-11-18}
  s.description = %q{This module generates XML Sitemaps for BrowserCMS Projects}
  s.email = %q{github@browsermedia.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
     "app/controllers/cms/sitemaps_controller.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/cms/sitemaps_helper.rb",
     "app/views/cms/shared/_admin_sidebar.html.erb",
     "app/views/cms/sitemaps/_sitemap_item.xml.erb",
     "app/views/cms/sitemaps/edit.html.erb",
     "app/views/cms/sitemaps/google.xml.erb",
     "app/views/layouts/templates/default.html.erb",
     "doc/README_FOR_APP",
     "lib/bcms_sitemap.rb",
     "lib/bcms_sitemap/routes.rb",
     "lib/bcms_sitemap/sitemap_generator.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://browsercms.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Sitemap Module for BrowserCMS}
  s.test_files = [
    "test/functional/cms/sitemaps_controller_test.rb",
     "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/helpers/cms/sitemaps_helper_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bcms_support>, [">= 0"])
    else
      s.add_dependency(%q<bcms_support>, [">= 0"])
    end
  else
    s.add_dependency(%q<bcms_support>, [">= 0"])
  end
end

